#!/usr/bin/env node
// Single source of truth for prototype navigation.
//
// Before this script, each screen-generator instance hand-wrote its own copy of the sidebar/topnav
// nav from the slice it was given — so a reorder, a rename, or an appended page reached only the
// one page that regenerated, and every other page (and index.html) drifted out of sync (see the
// html-generator-kit audit, finding #3). This script is the only thing that writes nav markup: it
// injects the SAME block into every page and index.html, and regenerates js/navigation.js's
// PAGES/NAV_GROUPS from the same data.
//
// Usage:
//   node wire-nav.mjs --dir <OUTPUT_DIR> --pages <pages.json> --nav <nav-structure.json> \
//     --title <AppTitle> [--layout sidebar|top-nav]
//
//   pages.json:        [{ id, title, domain, description }]
//   nav-structure.json: { domain: [pageId, ...] }
//
// What it does:
//   1. Writes {OUTPUT_DIR}/js/navigation.js (PAGES + NAV_GROUPS baked in as literals).
//   2. Injects nav HTML between `<!-- nav:start -->` / `<!-- nav:end -->` markers in
//      {OUTPUT_DIR}/index.html (href prefix `pages/`) and every {OUTPUT_DIR}/pages/*.html
//      (href prefix `./`).
//
// A page file with no marker pair is reported as an error (exit 1) rather than silently left with
// whatever nav it already had — a missing marker means the page-shell template drifted, and that
// must be visible, not swallowed.
//
// Exit code: 0 = all files wired, 1 = one or more files had no marker pair (or markers reversed), 2 = usage error.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

function flag(args, name) {
  const i = args.indexOf(`--${name}`)
  if (i < 0) return ''
  const next = args[i + 1]
  if (!next || next.startsWith('--')) return true
  return next
}

// ── domain → icon (single source; was duplicated prose in screen-generator.md + assembly-wiring.md) ──
const ICONS = [
  [/profile|people|user|resident|customer|member/, '👥'],
  [/document|file/, '📄'],
  [/note/, '📝'],
  [/client|account|bank/, '🏦'],
  [/analytic|report|metric/, '📊'],
  [/setting|config|preference/, '⚙️'],
  [/dashboard|overview|^home$/, '🏠'],
  [/notification|alert/, '🔔'],
  [/listing|item|catalog/, '📦'],
  [/request|order|booking/, '🤝'],
]
const DEFAULT_ICON = '•'
export function iconFor(domain) {
  const key = String(domain || '').toLowerCase()
  for (const [pattern, icon] of ICONS) if (pattern.test(key)) return icon
  return DEFAULT_ICON
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))
}

// ── nav markup (shared between index.html and pages/*.html; only the href prefix differs) ──
export function navHtml(pagesList, navStructure, linkPrefix) {
  const byId = new Map(pagesList.map((p) => [p.id, p]))
  const blocks = []
  for (const [domain, ids] of Object.entries(navStructure)) {
    const items = (ids || []).map((id) => byId.get(id)).filter(Boolean)
    if (!items.length) continue
    const links = items.map((p) =>
      `      <a href="${linkPrefix}${p.id}.html" class="nav-item" data-nav-id="${p.id}">${iconFor(p.domain)} ${escapeHtml(p.title)}</a>`
    ).join('\n')
    blocks.push(`    <div class="nav-group">\n      <p class="nav-group-label">${escapeHtml(domain)}</p>\n${links}\n    </div>`)
  }
  return blocks.join('\n')
}

// ── marker injection ──
const START = '<!-- nav:start -->'
const END = '<!-- nav:end -->'
export function injectNav(html, block) {
  const si = html.indexOf(START)
  const ei = html.indexOf(END)
  if (si === -1 || ei === -1 || ei < si) return null
  return `${html.slice(0, si + START.length)}\n${block}\n    ${html.slice(ei)}`
}

// ── js/navigation.js (active-page + breadcrumb helpers; PAGES/NAV_GROUPS are literals, not a
// template substitution, so there is never a leftover PAGES_ARRAY/NAV_GROUPS placeholder) ──
export function navigationJs(pagesList, navStructure) {
  const pagesLiteral = JSON.stringify(
    pagesList.map((p) => ({ id: p.id, title: p.title, domain: p.domain })),
    null, 2,
  ).replace(/^/gm, '  ').trim()
  const groupsLiteral = JSON.stringify(navStructure, null, 2).replace(/^/gm, '  ').trim()
  return `// Multi-page navigation — active state + breadcrumb helpers.
// Generated by scripts/wire-nav.mjs — do not hand-edit; re-run wire-nav.mjs instead.

const PAGES = ${pagesLiteral}

const NAV_GROUPS = ${groupsLiteral}

// ── Active page detection ────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  const pathname = window.location.pathname
  const currentId = PAGES.find((p) => pathname.endsWith(\`/\${p.id}.html\`) || pathname.endsWith(\`/\${p.id}\`))?.id

  if (currentId) {
    document.querySelectorAll(\`[data-nav-id="\${currentId}"]\`).forEach((el) => {
      el.classList.add('nav-item-active')
      el.setAttribute('aria-current', 'page')
    })
  }
})

// ── Helpers (available to inline Alpine expressions) ─────────────────
function getPageTitle(id) {
  return PAGES.find((p) => p.id === id)?.title ?? id
}

function getPageDomain(id) {
  return PAGES.find((p) => p.id === id)?.domain ?? ''
}

function getPagesInDomain(domain) {
  return PAGES.filter((p) => p.domain === domain)
}
`
}

// ── main (only runs when this file is executed directly, not when imported for its exports) ──
function main() {
  const args = process.argv.slice(2)
  const dir = String(flag(args, 'dir') || '')
  const pagesArg = String(flag(args, 'pages') || '')
  const navArg = String(flag(args, 'nav') || '')
  const title = String(flag(args, 'title') || 'Prototype')
  const layout = String(flag(args, 'layout') || 'sidebar')

  if (!dir || !pagesArg || !navArg) {
    console.error('usage: wire-nav.mjs --dir <OUTPUT_DIR> --pages <pages.json> --nav <nav-structure.json> --title <AppTitle> [--layout sidebar|top-nav]')
    process.exit(2)
  }
  if (!existsSync(dir)) {
    console.error(`FATAL: --dir not found: ${dir}`)
    process.exit(2)
  }

  let pages, nav
  try {
    pages = JSON.parse(readFileSync(pagesArg, 'utf8'))
  } catch (e) {
    console.error(`FATAL: could not read/parse --pages ${pagesArg}: ${e.message}`)
    process.exit(2)
  }
  try {
    nav = JSON.parse(readFileSync(navArg, 'utf8'))
  } catch (e) {
    console.error(`FATAL: could not read/parse --nav ${navArg}: ${e.message}`)
    process.exit(2)
  }
  if (!Array.isArray(pages) || pages.length === 0) {
    console.error('FATAL: --pages must be a non-empty JSON array')
    process.exit(2)
  }

  const errors = []

  const jsDir = join(dir, 'js')
  writeFileSync(join(jsDir, 'navigation.js'), navigationJs(pages, nav))

  const indexPath = join(dir, 'index.html')
  if (existsSync(indexPath)) {
    const html = readFileSync(indexPath, 'utf8')
    const injected = injectNav(html, navHtml(pages, nav, 'pages/'))
    if (injected === null) errors.push(`index.html: no <!-- nav:start/end --> marker pair found`)
    else writeFileSync(indexPath, injected)
  } else {
    errors.push('index.html: not found')
  }

  const pagesDir = join(dir, 'pages')
  let wiredCount = 0
  if (existsSync(pagesDir)) {
    const block = navHtml(pages, nav, './')
    for (const entry of readdirSync(pagesDir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.html')) continue
      const p = join(pagesDir, entry.name)
      const html = readFileSync(p, 'utf8')
      const injected = injectNav(html, block)
      if (injected === null) errors.push(`pages/${entry.name}: no <!-- nav:start/end --> marker pair found`)
      else { writeFileSync(p, injected); wiredCount += 1 }
    }
  } else {
    errors.push('pages/ directory not found')
  }

  console.log(`OK: navigation.js written, ${wiredCount} page(s) + index.html wired (title: "${title}", layout: ${layout})`)
  if (errors.length) {
    console.error(`\nERRORS (${errors.length}):`)
    errors.forEach((e) => console.error(`  ✗ ${e}`))
    process.exit(1)
  }
}

const isMain = (() => {
  try { return process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1] } catch { return false }
})()
if (isMain) main()
